from typing import Protocol


class Storage(Protocol):
    def save(self, data: bytes, extension: str) -> str: ...
    def open(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
