"""Space model for the local 2D editor and 3D preview.

Everything here is authoritative backend data. Room and object identities are
generated by the backend and persisted, so a binding can survive a reload and
can be invalidated when a room is split, merged or deleted. Browser storage is
only ever a temporary draft.
"""

import hashlib
import json
from datetime import UTC, datetime
from enum import Enum

from pydantic import Field, model_validator

from alignspace.domain.base import DomainModel, NonBlankString
from alignspace.domain.enums import Role
from alignspace.domain.space_catalog import MATERIAL_OPTIONS, Approximation, MaterialTarget

SCHEMA_VERSION = "1.0.0"
UNITS = "mm"
MIN_DIMENSION = 1000.0
MAX_DIMENSION = 20000.0
MAX_ROOMS = 12
MAX_OBJECTS = 200
ROOM_TYPES = ("living_room", "bedroom", "kitchen", "bathroom", "study", "other")


class SpaceError(ValueError):
    """Raised when a space document is structurally invalid."""


class Point(DomainModel):
    x: float = 0.0
    y: float = 0.0


class RoomSize(DomainModel):
    width: float
    depth: float


class Wall(DomainModel):
    id: str
    start: Point
    end: Point
    thickness: float = 100.0


class Floor(DomainModel):
    id: str
    material_option_id: str | None = None
    binding_id: str | None = None


class Room(DomainModel):
    id: str
    name: NonBlankString
    room_type: str = "living_room"
    origin: Point = Field(default_factory=Point)
    size: RoomSize
    walls: list[Wall] = Field(default_factory=list)
    floor: Floor


class SpaceObject(DomainModel):
    id: str
    room_id: str
    kind: str = "furniture"
    label: str = ""
    geometry: dict[str, object] = Field(default_factory=dict)


class SpacePlan(DomainModel):
    schema_version: str = SCHEMA_VERSION
    units: str = UNITS
    rooms: list[Room] = Field(default_factory=list)
    objects: list[SpaceObject] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_plan(self) -> "SpacePlan":
        if len(self.rooms) > MAX_ROOMS:
            raise ValueError(f"a space plan supports at most {MAX_ROOMS} rooms")
        if len(self.objects) > MAX_OBJECTS:
            raise ValueError(f"a space plan supports at most {MAX_OBJECTS} objects")
        seen: set[str] = set()
        room_ids: set[str] = set()
        for room in self.rooms:
            _validate_dimension(room.size.width, room.size.depth)
            room_ids.add(room.id)
            for identifier in (room.id, room.floor.id, *(wall.id for wall in room.walls)):
                if identifier in seen:
                    raise ValueError(f"duplicate space object id {identifier}")
                seen.add(identifier)
            if room.room_type not in ROOM_TYPES:
                raise ValueError(f"unsupported room type {room.room_type}")
            material_id = room.floor.material_option_id
            if material_id is not None:
                option = MATERIAL_OPTIONS.get(material_id)
                if option is None or MaterialTarget.FLOOR not in option.targets:
                    raise ValueError(
                        f"floor material {material_id!r} is not a supported floor option"
                    )
        for item in self.objects:
            if item.id in seen:
                raise ValueError(f"duplicate space object id {item.id}")
            seen.add(item.id)
            if item.room_id not in room_ids:
                raise ValueError(f"object {item.id} references an unknown room")
        return self


def _validate_dimension(width: float, depth: float) -> None:
    for value in (width, depth):
        if not MIN_DIMENSION <= value <= MAX_DIMENSION:
            raise ValueError(
                f"room dimensions must be between {MIN_DIMENSION:.0f}mm and "
                f"{MAX_DIMENSION:.0f}mm"
            )


def calculate_space_content_hash(payload: dict[str, object]) -> str:
    canonical = json.dumps(
        payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def build_rectangular_room(
    *,
    room_id: str,
    name: str,
    width: float,
    depth: float,
    room_type: str = "living_room",
) -> Room:
    """Create a rectangular room from dimensions. No plan-reading is involved."""
    _validate_dimension(width, depth)
    corners = {
        "north": (Point(x=0, y=0), Point(x=width, y=0)),
        "east": (Point(x=width, y=0), Point(x=width, y=depth)),
        "south": (Point(x=width, y=depth), Point(x=0, y=depth)),
        "west": (Point(x=0, y=depth), Point(x=0, y=0)),
    }
    walls = [
        Wall(id=f"wall-{room_id}-{side}", start=start, end=end)
        for side, (start, end) in corners.items()
    ]
    return Room(
        id=room_id,
        name=name,
        room_type=room_type,
        size=RoomSize(width=width, depth=depth),
        walls=walls,
        floor=Floor(id=f"floor-{room_id}"),
    )


SPACE_SOURCES = (
    "rectangular_dimensions",
    "manual_edit",
    "material_application",
    "binding",
    "rollback",
)


class SpaceVersion(DomainModel):
    """An immutable space plan version with its own hash and provenance."""

    version: int = Field(ge=1)
    content_hash: str
    payload: dict[str, object]
    created_by: str
    created_role: Role
    source: str
    previous_version: int | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @model_validator(mode="after")
    def validate_content_hash(self) -> "SpaceVersion":
        if self.content_hash != calculate_space_content_hash(self.payload):
            raise ValueError("content_hash must match canonical space payload SHA-256")
        return self


class BindingTarget(str, Enum):
    FLOOR = "floor"


class BindingStatus(str, Enum):
    ACTIVE = "active"
    NEEDS_REVIEW = "needs_review"
    INVALIDATED = "invalidated"


class SpaceBinding(DomainModel):
    """A confirmed preference mapped onto a supported space material.

    ``needs_review`` is set when the referenced room changes identity or the
    underlying preference changes. Nothing is transferred silently.
    """

    id: str
    room_id: str
    floor_object_id: str | None = None
    target: BindingTarget = BindingTarget.FLOOR
    attribute_id: str | None = None
    candidate_id: str | None = None
    material_option_id: str
    approximation: Approximation
    note: str = ""
    status: BindingStatus = BindingStatus.ACTIVE
    bound_by: str
    bound_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    space_version: int = Field(ge=1)
    applied_space_version: int | None = None


class SpaceApproval(DomainModel):
    """A joint brief+space approval, separate from the brief-only approval."""

    id: str
    role: Role
    actor_id: NonBlankString
    brief_version: int = Field(ge=1)
    brief_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    space_version: int = Field(ge=1)
    space_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    approved_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


def invalidate_bindings(
    bindings: list[SpaceBinding],
    *,
    room_id: str | None = None,
    attribute_id: str | None = None,
) -> list[SpaceBinding]:
    """Move active bindings touching a changed room/preference to needs_review.

    Room split/merge/delete and preference edits change the identity a binding
    was based on, so the binding must be re-confirmed rather than silently
    transferred.
    """

    result: list[SpaceBinding] = []
    for binding in bindings:
        touched = (room_id is not None and binding.room_id == room_id) or (
            attribute_id is not None and binding.attribute_id == attribute_id
        )
        if touched and binding.status is BindingStatus.ACTIVE:
            result.append(
                binding.model_copy(update={"status": BindingStatus.NEEDS_REVIEW})
            )
        else:
            result.append(binding)
    return result
