from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import json
import re
import hashlib
from app import interview, engine
from app.language import SEARCH_ALIASES
root=Path('app/static')
data={}
for line in (root/'locale-zh.txt').read_text(encoding='utf-8-sig').splitlines():
 if '|' in line:
  en,zh=line.split('|',1);data[en]=zh
for q in interview.DETAIL_QUESTIONS:
 data[q['prompt']]=q['promptZh'];data[q['rationale']]=q['rationaleZh'];data.update(q['optionsZh'])
for values in engine.REFERENCE_KEYWORDS.values():
 for value, aliases in values.items():
  zh=engine._ZH_ALIASES.get(value)
  if zh:data[value.replace('_',' ')]=zh[0]
handbook = Path('app/knowledge_data/handbook.json')
if hashlib.sha256(handbook.read_bytes()).hexdigest() != '29cb7dfb3f168bd184b68e23781b611086665fbdc039329a678c6b8f7179e539':
 raise ValueError('Handbook changed: review translated source descriptions before updating the snapshot hash')
records=json.loads(Path('app/knowledge_data/handbook.json').read_text(encoding='utf-8'))['records']
# Prevent translations from silently attaching to changed or reordered source paragraphs.
expected_ids = ['d1d7d4ea9b2f23f8', '5620048c4be2de12', '3dcdb8c044a3a11e', '1a655671303c8fd9', '342dab15ae933f9e', 'b639bcd463f324d8', 'e8b4b066cf3db6e8', '6b3b0c607619394a', 'fc062531649fb198', '327ac673a755ed24', 'a52c48745b541183', '76dc299c68daeb0a', '579dc23eb7347901', '4ddcd188b8cfa204', 'd7818904ffd35f25', '59d218a89dd1f5a0', '735835efad1c70e0', '7b0b9c7a7a04cc50', '127ae2ffa16ffa39', '20768ebb956e1da5', '9b931a0f1c595f5c', '61c5d02653aefdb6']
if [r['id'] for r in records] != expected_ids:
 raise ValueError('Handbook changed: review Chinese descriptions before rebuilding the locale')
summaries=[
'北欧设计把有机形态与日常功能结合，强调自然材质的触感、温暖灯光和舒适相处的氛围。可观察浅木地面、米白墙面、羊毛织物、少量深色点缀，以及多个小光源如何共同营造空间。',
'此摘录列举浅纹橡木、白蜡木和桦木，羊毛与亚麻等天然织物，可随时间变化的皮革、哑光陶器，以及做旧或拉丝黄铜。部分案例也结合石灰刷砖与裸露混凝土。它们是案例中的材料语言，不是必须全部采用的清单。',
'侘寂重视不完美、非永久与未完成之美，关注朴素、非对称、自然旧化和时间痕迹。住宅中可通过柔和大地色、手工表面、少量有年代感的物件以及带有情绪的光线表达。',
'摘录举例包括手工抹灰、保留模板痕迹的混凝土、旧木、未经漂白的亚麻与麻布、无釉陶器，以及带有自然断面和凿痕的石材。光线也被视为塑造空间的材料。这些是来源的审美描述，适用性仍需结合实际使用讨论。',
'MUJI 极简强调普通物件、日常使用和能够容纳生活的留白。空间可围绕朴素木材、纸白墙面、克制的织物色彩与自然光展开。物件的选择应来自真实使用，而不只是为了看起来像某种风格。',
'此摘录讨论未经明显修饰的软木与胶合板、水泥或砂浆地面、低饱和的棉麻织物、朴素陶瓷以及纸质元素。核心观察是材料与用途是否直接、自然，而不是叠加装饰效果。',
'现代极简强调通过删减接近空间的本质，以比例、光线与触感替代过多装饰。它不必是冷白的空盒子，也可以通过一两种自然材料、暖木和少量精心摆放的物件营造温暖。',
'摘录列举石灰抹灰、宽板天然橡木、石灰岩等石材、连续水磨石地面，以及少量有鲜明纹理的大理石和织物。可以观察连续表面、材料比例和少数重点物件如何保持空间的安静感。',
'静奢强调克制、工艺、能随时间变化的材料和舒适感，而非显眼符号。来源描述了哑光矿物墙面、烟熏或石灰处理橡木、亚麻与圈绒座椅，以及少量有意摆放的艺术品。',
'材料示例包括矿物抹灰、烟熏橡木、亚麻与羊毛等织物、哑光石材、自然氧化的青铜或黄铜和手工陶器。观察重点是细腻质感、同色层次与工艺，而不是把这些材料视为唯一正确的选择。',
'工业阁楼源于旧工厂和仓库的住宅化使用，重视可见结构、原砖墙、大窗与使用痕迹。案例会将木梁、金属构件、旧座椅和工业形态灯具结合。住宅是否具备这些结构，应以实际现场为准。',
'摘录讨论旧砖、铸铁柱与木梁、压花金属天花、宽木地板、黑色钢窗、做旧皮革、实用石材台面和管件或玻璃球灯具。这些共同表达建筑原有结构与使用历史。',
'中古现代设计将战后新材料与有机、雕塑化形态结合。住宅案例常见开放布局、大面积玻璃、暖木表面及少量造型鲜明的家具，并以原色或大地色点缀。',
'材料示例包括胡桃木、柚木、成型胶合板、玻璃纤维、铸铝与铬金属底座、钢框、大面积玻璃、砖以及小规格瓷砖。重点是工业材料、温暖木材和家具曲线之间的组合。',
'色彩观感依赖周围环境，不能只看孤立色样。阿尔伯斯的色彩研究讨论颜色之间的相互影响，包括明度、饱和度、冷暖、边界和透明错觉。',
'这一段引出后续关于材质配色的实践说明：评估色样时需要同时考虑它周围的颜色。',
'同一块灰色在冷色背景旁可能显暖，在暖色背景旁可能显冷。高饱和互补色相邻时可能产生强烈的视觉边界，可降低一方饱和度或加入中性色过渡。应在实际相邻材料与光线中重新判断色样。',
'描述色彩可以分开讨论色相、明度和饱和度。红橙黄通常归入暖色，蓝绿紫通常归入冷色。实体标准色样有助于沟通颜色，但仍需核对实际材料与照明。',
'来源以咖啡馆为例，将深绿主色、胡桃木与黄铜暖色和偏冷紫色组合，再用暖琥珀光改变整体观感。这是特定场景的配色示例，不是你家必须采用的色值或灯光要求。',
'常用照明讨论可分为环境光、重点光和任务光；设计实践还常单列装饰光，用于描述灯具本身作为视觉物件的作用。不同层次可以分别支持通行、聚焦、阅读与氛围。',
'环境光提供基础可见度；重点光引导注意；任务光服务阅读或操作；装饰光强调灯具的视觉存在。原表还列有示例照度，但来源已说明其中部分仅属经验，不能直接作为本项目的照明规范或现场设计值。',
'四层划分属于室内设计的常用实践，并非某个单一标准中的编号条文。与设计师沟通时，应将它当作讨论照明作用的方法，而不是法规要求。'
]
for i,(r,zh) in enumerate(zip(records,summaries,strict=True)):
 data[r['text']]='中文释义（根据参考摘录整理）：'+zh
 title=r['title']
 title_zh=['北欧风','日式侘寂','MUJI 极简','现代极简','静奢','工业阁楼','中古现代'][i//2] if i<14 else ('材料与色彩' if i<19 else '照明设计')
 data[title]=title_zh
 data[r['verification']]='参考资料来自第三方设计手册。其引用和设计主张未经本项目逐条独立验证，仅用于讨论，不作为规范或适用性保证。'
for en, zh in list(data.items()):
 if len(en) < 100:
  data.setdefault(en.title(), zh)
  data.setdefault(re.sub(r"\b\w", lambda m: m[0].upper(), en), zh)
# Compile the checked-in phrase catalogue; no remote translation service or user data transfer.
(root/'locale-data.js').write_text('/* Generated by scripts/build_locale.py. */\nwindow.AlignLocale = '+json.dumps(data,ensure_ascii=False,indent=2)+';\nwindow.AlignSearchAliases = '+json.dumps(SEARCH_ALIASES,ensure_ascii=False)+';\n',encoding='utf-8')
